### ISSUE TITLE
cocos2d is so bad

### ISSUE THREAD

**Issue by enpinzolas** [Kelossus/King-of-the-Dungeon#1]
but really, haxe fliskel is better, and haxe fliskel is REAL bad.

**Comment by oersted** [comment]
:)

**Comment by oersted** [comment]
Martxan jartzen saiatzen aritu naiz. Hainbat png eta wav eztaude repoan. Gauza batzuk deprekatuta egon dira 2015tik. Azkenean segmentation fault bat eman dit eta errenditu naiz :joy: :joy: RIP in Peace

**Comment by enpinzolas** [comment]
😂😂 Dibertigarria izan zen, bai
